services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ros2_ws:/ros2_ws
      - uv_cache:/root/.cache/uv
      - pip_cache:/root/.cache/pip
      - pre-commit_cache:/root/.cache/pre-commit
    tty: true
    stdin_open: true
    command: /usr/bin/bash
    stop_grace_period: 0s
    working_dir: /ros2_ws/src/pamiq_core

volumes:
  ros2_ws:
    name: ros2_ws_pamiq_ros
  uv_cache:
  pip_cache:
  pre-commit_cache:
